export const dilate=(p,c,k)=>p.map((v,i)=>c[i]+k*(v-c[i]));
export const slope=(a,b)=>b[0]===a[0]?null:(b[1]-a[1])/(b[0]-a[0]);
export const missions=[
{id:'brace',type:'scale',title:'The broken brace',zone:'DOCK 01',story:'The rover’s docking arm is missing a brace. Enlarge the printed prototype until all three corners meet the sockets.',points:[[0,0],[2,0],[2,1]],center:[0,0],k:2,pin:1,prompt:'Before printing: where will the far-right bottom corner land?',why:'Every distance from the center doubles. The brace keeps its angles; its lengths double.',hints:['Follow the ray from the center through each corner.','The corner is 2 units to the right of the center. Double that distance.','Use k = 2. The corner lands at (4, 0).']},
{id:'mini',type:'scale',title:'A smaller housing',zone:'DOCK 02',story:'A sensor housing blocks the charging port. Reduce the whole housing to fit the smaller socket pattern.',points:[[0,0],[6,0],[6,4]],center:[0,0],k:.5,pin:2,prompt:'Predict the top-right corner after reducing to half size.',why:'A factor of ½ halves every distance from the center. It does not subtract the same amount from each coordinate.',hints:['A reduction has a positive factor less than 1.','Half of 6 is 3; half of 4 is 2.','Use k = ½. The corner lands at (3, 2).']},
{id:'offset',type:'scale',title:'Pin the hinge',zone:'DOCK 03',story:'This brace must shrink around its hinge at (2, 1). Choose the right center, then fit the three sockets.',points:[[2,1],[6,1],[6,3]],center:[2,1],centers:[[0,0],[2,1],[4,2]],k:.5,pin:2,prompt:'The hinge stays at (2, 1). Where will the upper corner land?',why:'Measure from the hinge: (4, 2) becomes (2, 1), then add the hinge back. New corner: (4, 2).',hints:['The chosen center stays fixed during a dilation.','Start at (2, 1). Take half of the vector (4, 2).','Choose center (2, 1), k = ½; upper corner (4, 2).']},
{id:'center',type:'scale',title:'Same scale, new anchor',zone:'DOCK 04',story:'The socket bracket moved. Keep the factor at ½, but move the dilation center to (4, 2) to shift the final part.',points:[[2,1],[6,1],[6,3]],center:[4,2],centers:[[0,0],[2,1],[4,2]],k:.5,pin:0,prompt:'At half size around (4, 2), where does the lower-left corner go?',why:'Changing the center changes the image. (2, 1) is (−2, −1) from (4, 2); half that vector gives (3, 1.5).',hints:['The factor is the same as the last repair; the anchor is different.','Halfway between (4, 2) and (2, 1) is the new corner.','Choose center (4, 2), k = ½; corner (3, 1.5).']},
{id:'check-scale',type:'scale',title:'Fresh print challenge',zone:'DOCK 05 · CHECK',story:'Repair the last brace with a new blueprint. Try it independently first. A clean repair checks your understanding here; it is not a school grade.',points:[[1,1],[3,1],[3,3]],center:[1,1],centers:[[0,0],[1,1],[3,3]],k:1.5,pin:2,prompt:'Around (1, 1), predict the upper corner when k = 1½.',why:'The vector (2, 2) grows to (3, 3). Add center (1, 1): (4, 4). All side lengths scale by 1½.',hints:['Use new point = center + k × (old point − center).','The corner is 2 right and 2 up from the center.','Choose center (1, 1), k = 1½; corner (4, 4).']},
{id:'ramp',type:'ramp',title:'Climb to the battery',zone:'TRAIL 01',story:'The battery is 3 units above the rover. The rover can climb at most ½ unit for every unit forward. Build a ramp using the available 6 units of space.',a:[0,0],b:[6,3],start:[3,3],prompt:'Predict the slope of a safe ramp rising 3 over a run of 6.',prediction:'½',choices:['½','2','3'],why:'Rise ÷ run = 3 ÷ 6 = ½. A shorter run with the same rise makes a steeper ramp.',hints:['Keep the height at 3. Extend the run to make the ramp gentler.','A rise of 3 needs a run of at least 6 for slope ½.','Move the endpoint to (6, 3). Slope = 3/6 = ½.']},
{id:'downhill',type:'ramp',title:'The downhill crossing',zone:'TRAIL 02',story:'Connect the upper platform to the lower platform. The rover moves right as the ramp drops.',a:[0,4],b:[6,1],start:[3,3],prompt:'Moving right, does this ramp have positive or negative slope?',prediction:'Negative',choices:['Positive','Negative','Zero'],why:'Rise is −3 and run is 6, so slope is −3/6 = −½. Downward as you move right means negative slope.',hints:['The destination is 3 units lower than the start.','Use signed rise: 1 − 4 = −3.','Move the endpoint to (6, 1). Slope = −½.']},
{id:'flat',type:'ramp',title:'Bridge the gap',zone:'TRAIL 03',story:'Build a level bridge to the next platform. A long bridge can still have zero steepness.',a:[0,2],b:[6,2],start:[3,4],prompt:'A level bridge has which slope?',prediction:'Zero',choices:['Zero','6','Undefined'],why:'Rise is 0 and run is 6. Slope = 0/6 = 0. Length and steepness are different measurements.',hints:['Both ends must be at the same height.','A horizontal line has no change in y.','Move the endpoint to (6, 2). Slope = 0.']},
{id:'lift',type:'ramp',title:'Switch to lift mode',zone:'TRAIL 04',story:'There is no room to move sideways. Connect the vertical lift cable. This is a lift, not a drivable ramp.',a:[3,0],b:[3,5],start:[6,3],prompt:'A vertical cable has a run of 0. What is its slope?',prediction:'Undefined',choices:['Zero','5','Undefined'],why:'Slope would require 5/0. Division by zero is undefined; a vertical line does not have slope 0.',hints:['Line the endpoint up directly above the start.','For a vertical line, x does not change.','Move the endpoint to (3, 5). Run = 0, so slope is undefined.']},
{id:'same-slope',type:'scaleRamp',title:'A bigger ramp?',zone:'TRAIL 05 · EXPERIMENT',story:'The original ramp is too steep. Test a uniformly enlarged copy first, then redesign its run to make it safe.',a:[0,0],b:[3,3],target:[6,3],prompt:'If both rise and run double, what happens to slope?',prediction:'Stays the same',choices:['Gets gentler','Stays the same','Gets steeper'],why:'Uniform dilation multiplies rise and run by the same positive factor: 6/6 = 3/3 = 1. To get slope ½, keep rise 3 and extend run to 6.',hints:['Uniform scaling changes lengths, not the ratio rise/run.','After testing the larger copy, change only the run.','Test k = 2 first. Then build to (6, 3), giving slope ½.']},
{id:'check-ramp',type:'ramp',title:'Rover launch challenge',zone:'TRAIL 06 · CHECK',story:'One final independent repair. Launch from (1, 1) to (5, 3), then explain the ramp using rise and run.',a:[1,1],b:[5,3],start:[3,5],prompt:'From (1, 1) to (5, 3), predict rise ÷ run.',prediction:'2/4 = ½',choices:['3/5','2/4 = ½','4/2 = 2'],why:'Subtract the endpoints: rise = 3 − 1 = 2; run = 5 − 1 = 4. Slope = 2/4 = ½.',hints:['Use changes in coordinates, not the destination coordinates alone.','Rise = y₂ − y₁; run = x₂ − x₁.','Move to (5, 3). Rise 2, run 4, slope ½.']}
];
export const goal=m=>m.type==='scale'?m.points.map(p=>dilate(p,m.center,m.k)):m.b;
export const near=(a,b)=>Math.abs(a-b)<.001;
export const fits=(m,s)=>m.type==='scale'?m.points.every((p,i)=>dilate(p,s.center,s.k).every((v,j)=>near(v,goal(m)[i][j]))):s.end.every((v,i)=>near(v,(m.target||m.b)[i]));
