'use strict';
// Business invitation address verified from Wix. No account data or credentials are collected.
const email='brian@olsenautomation.com',key='olsen-automation-client-setup-v1';
let state={step:0,invite:false},persistent=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&typeof saved==='object'){state.step=[0,1,2].includes(saved.step)?saved.step:0;state.invite=saved.invite===true;}}catch{persistent=false;}
const active=document.querySelector('#active'),notice=document.querySelector('#notice');
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{persistent=false;}document.querySelector('#storage').textContent=persistent?'Public guide · progress stays on this device · self-reported':'Public guide · progress is temporary · device storage unavailable';}
function go(step){state.step=step;notice.textContent='';save();render();active.focus();}
const names=['Welcome','Invite Brian','Brian reviews & prepares'];
function render(){document.querySelector("#visual-guide").hidden=state.step!==1;document.querySelector('#steps').innerHTML=names.map((n,i)=>{const done=state.step>i&&(i===0||state.invite);return `<li class="${state.step===i?'current':done?'done':''}" ${state.step===i?'aria-current="step"':''}><span class="num">${done?'✓':i+1}</span><strong>${n}</strong><small>${i===0?'A quick overview of what to expect.':i===1?(state.invite?'Reported sent · access pending':'Give Brian editing access through Wix.'):'Account review and handoff stay pending.'}</small></li>`;}).join('');
if(state.step===0){active.innerHTML=`<div class="welcome"><div class="web-icon" aria-hidden="true">WIX</div><h2 id="step-title">Your website. Your ownership.</h2><p>We’ll guide you through inviting Brian to your Wix website. He can prepare the updates while you keep control of your existing site.</p><button class="primary" id="start">Start setup <span aria-hidden="true">→</span></button><p class="small">A few simple steps. No password sharing.</p></div>`;document.querySelector('#start').onclick=()=>go(1);}
if(state.step===1){active.innerHTML=`<p class="status">Step 2 of 3 · ${state.invite?'Invite reported sent · access pending':'Invitation pending'}</p><h2 id="step-title">Invite Brian in Wix.</h2><p>Open your Wix dashboard and select the website you own.</p><ol class="instructions"><li>Go to <strong>Settings → Roles & Permissions</strong>.</li><li>Choose <strong>Invite Collaborators</strong>.</li><li>Enter Brian’s business invitation email below.</li><li>Select <strong>Website Manager</strong> and review its permissions.</li><li>Choose <strong>Send Invite</strong> in Wix.</li></ol><p class="small">Website Manager allows site management, editing and publishing without billing or ownership control. If a seat or additional permission is needed, pause and ask Brian.</p><label for="email">Brian’s invitation email</label><input id="email" type="text" readonly value="${email}"><button id="copy">Copy email</button><a class="button" href="https://www.wix.com/dashboard" target="_blank" rel="noopener noreferrer">Open Wix dashboard ↗</a><label class="check"><input type="checkbox" id="invite" ${state.invite?'checked':''}><span>I sent the invitation in Wix.<br><small>Your report only. This page cannot verify it.</small></span></label><div class="actions"><button id="back">← Back</button><button id="next" class="primary" ${state.invite?'':'disabled'}>Next →</button></div><button id="review" class="link">Review what happens next</button><p class="small"><a href="https://support.wix.com/en/article/inviting-people-to-contribute-to-your-site" target="_blank" rel="noopener noreferrer">Wix invitation instructions ↗</a></p>`;document.querySelector('#copy').onclick=async()=>{const field=document.querySelector('#email');try{await navigator.clipboard.writeText(email);notice.textContent='Email copied.';}catch{field.focus();field.select();notice.textContent='Copy unavailable. The email is selected; use your device’s Copy command.';}};document.querySelector('#back').onclick=()=>go(0);document.querySelector('#next').onclick=()=>go(2);document.querySelector('#review').onclick=()=>go(2);document.querySelector('#invite').onchange=e=>{state.invite=e.target.checked;save();document.querySelector('#next').disabled=!state.invite;document.querySelector('.status').textContent=state.invite?'Step 2 of 3 · Invite reported sent · access pending':'Step 2 of 3 · Invitation pending';};}
if(state.step===2){active.innerHTML=`<p class="status">Step 3 of 3 · ${state.invite?'Reported sent · awaiting Brian’s acceptance':'Invitation still pending'}</p><h2 id="step-title">Brian takes it from here.</h2><p>${state.invite?'Your invitation is marked sent on this device. Brian still needs to accept it in Wix and confirm the actual access.':'You can preview the next stage here. Brian still needs a real invitation and account access.'}</p><p>Brian will check your site, editor and plan, then recommend the right path. You’ll review the proposed changes before launch.</p><p>If a replacement site is appropriate, you may need to accept ownership and reassign a compatible plan in Wix. Brian will guide you after the account review. This page cannot migrate a site or change a plan.</p><p class="warning">Pending: Brian’s account review and your approval.<br>No ownership, plan or domain changes have happened here.</p><details><summary>What Brian prepares next</summary><p>Brian checks editor and plan compatibility, keeps existing URLs or maps redirects, and prepares domain, business email and contact-form checks before a separately approved launch.</p><p>Cross-editor migration is not automatic. A Wix Premium plan needs a Studio plan upgrade for a Studio site. Collaborators cannot transfer ownership, duplicate/delete sites or assign/reassign Premium plans.</p><p><a href="https://support.wix.com/en/article/information-for-site-contributors" target="_blank" rel="noopener noreferrer">Wix collaborator limits ↗</a> · <a href="https://support.wix.com/en/article/assigning-a-premium-plan-to-a-different-site-in-your-wix-account" target="_blank" rel="noopener noreferrer">Plan guidance ↗</a></p></details><div class="actions"><button id="back">← Back</button><button id="overview" class="primary">Back to overview</button></div>`;document.querySelector('#back').onclick=()=>go(1);document.querySelector('#overview').onclick=()=>go(0);}}
document.querySelector('#reset').onclick=()=>{state={step:0,invite:false};try{localStorage.removeItem(key);}catch{}render();notice.textContent='On-device progress reset. Wix has not been changed.';};save();render();
